[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
libs = []
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"
bytecode_hash = "ipfs"
auto_detect_remappings = false
fs_permissions = [{ access = "read", path = "./fork-source.json" }]

[profile.default.fuzz]
runs = 64
seed = "0xec0"

[fmt]
line_length = 110
